-- PRODX ERP — row level security (ADR 0002 tenancy, ADR 0003 scope)
--
-- Run after `prisma migrate deploy`, as the schema OWNER.
-- The prodx_app role is created by scripts/create-app-role.sql, which requires
-- a password. No credential appears in this file.
--
-- Two dimensions are enforced here:
--   tenant — which company's data      (app.tenant_id)
--   plant  — which factories within it (app.plant_scope)
--
-- Permissions decide WHICH ACTIONS a user may take and live in the application
-- guard; scope decides WHICH DATA they may touch and lives here, because a
-- forgotten WHERE clause must degrade performance, never disclose a factory.
--
-- Why FORCE: the owning role bypasses RLS by default, and Prisma is commonly
-- pointed at the owner. FORCE closes that, and the application additionally
-- connects as prodx_app, which owns nothing.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prodx_app') THEN
    RAISE EXCEPTION
      'Role prodx_app does not exist. Run scripts/create-app-role.sql first.';
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO prodx_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO prodx_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prodx_app;

-- ── scope helpers ───────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION app_tenant() RETURNS uuid AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$ LANGUAGE sql STABLE;

/**
 * NULL means "every plant" and is reached only by the explicit '*' sentinel.
 * An unset or empty setting returns an EMPTY array, which matches nothing —
 * so a code path that forgets to establish scope sees no plant data at all.
 * Failing closed turns that mistake into an obvious empty screen during
 * development rather than a cross-factory disclosure in production.
 */
CREATE OR REPLACE FUNCTION app_plant_scope() RETURNS uuid[] AS $$
  SELECT CASE
    WHEN current_setting('app.plant_scope', true) = '*' THEN NULL
    WHEN coalesce(current_setting('app.plant_scope', true), '') = '' THEN ARRAY[]::uuid[]
    ELSE string_to_array(current_setting('app.plant_scope', true), ',')::uuid[]
  END
$$ LANGUAGE sql STABLE;

-- ── policies ────────────────────────────────────────────────────────────────
--
-- Generated by introspection rather than a hand-written list, so a new table
-- cannot be forgotten. Three shapes:
--   the plant table itself   — scoped on its own id
--   tables with plant_id     — scoped on that column; NULL means "all plants",
--                              which is how an approval rule applies group-wide
--   everything else          — tenant only

DO $$
DECLARE
  t          text;
  has_plant  boolean;
  predicate  text;
BEGIN
  FOR t IN
    SELECT c.relname
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_attribute a ON a.attrelid = c.oid
     WHERE n.nspname = 'public'
       AND c.relkind = 'r'
       AND a.attname = 'tenant_id'
       AND NOT a.attisdropped
  LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_attribute a
        JOIN pg_class c2 ON c2.oid = a.attrelid
        JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
       WHERE n2.nspname = 'public' AND c2.relname = t
         AND a.attname = 'plant_id' AND NOT a.attisdropped
    ) INTO has_plant;

    IF t = 'plant' THEN
      predicate := 'tenant_id = app_tenant()
                    AND (app_plant_scope() IS NULL OR id = ANY(app_plant_scope()))';
    ELSIF has_plant THEN
      predicate := 'tenant_id = app_tenant()
                    AND (app_plant_scope() IS NULL
                         OR plant_id IS NULL
                         OR plant_id = ANY(app_plant_scope()))';
    ELSE
      predicate := 'tenant_id = app_tenant()';
    END IF;

    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE  ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON public.%I USING (%s) WITH CHECK (%s)',
      t, predicate, predicate);
  END LOOP;
END
$$;

-- ── immutability ────────────────────────────────────────────────────────────
-- Reversal is the only correction for these tables (CLAUDE.md invariant 2).

CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'Table % is append-only. Reverse the entry instead of % it.',
    TG_TABLE_NAME, lower(TG_OP);
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'stock_ledger_entry', 'stock_unit_link', 'journal_entry', 'journal_line', 'audit_event',
    -- A gate or weighbridge record states what physically happened. A correction
    -- is a new event; an approval is a fact about who decided what, and when.
    'gate_event', 'weighbridge_ticket', 'approval_record'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_append_only ON public.%I', t, t);
    EXECUTE format(
      'CREATE TRIGGER %I_append_only BEFORE UPDATE OR DELETE ON public.%I
         FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation()', t, t);
  END LOOP;
END
$$;
