const domains=window.PRODX_DOMAINS||[];
const icons=["⌂","▦","◎","⌁","⌑","▣","⚙","≋","▤","✓","⌘","₹","♙","◫"];
let currentGroup=0,currentPage=0,currentView="list",lineNo=3;
const $=id=>document.getElementById(id);

const commonFields=[
  ["Document Number","text","Auto generated"],["Document Date","date",""],["Plant / Site","select",["Plant 01 - Ahmedabad","Plant 02 - Surat","Plant 03 - Bhiwandi"]],
  ["Owner / Department","select",["Operations","Planning","Purchase","Quality","Maintenance","Finance"]],["Status","select",["Draft","Open","Pending Approval","Approved","Closed"]],["Priority","select",["Normal","High","Urgent"]],
  ["Reference Number","text","Customer / supplier reference"],["Effective From","date",""],["Remarks","textarea","Enter notes, reason or instruction"]
];
const fieldSets={
  textile:[["Style / Fabric Code","text","e.g. FAB-CTN-40S-001"],["Color / Shade","text","Navy 19-4024"],["Size / Width","text","58 inches"],["Yarn Count / Blend","text","40s / 100% Cotton"],["GSM","number","180"],["Roll / Batch Number","text","LOT-2408-017"],["Process","select",["Weaving","Knitting","Dyeing","Printing","Finishing","Inspection","Cutting","Sewing"]],["Machine / Loom","select",["Loom-01","Loom-02","Dyeing-04","Stenter-02"]],["Target Quantity","number","5000"],["UoM","select",["Meter","Kg","Piece","Roll"]],["Shrinkage Tolerance","text","± 3%"],["Shade Approval","select",["Not Required","Pending","Approved"]]],
  carton:[["Box / Board Code","text","e.g. BX-5PLY-001"],["FEFCO Style","select",["0201 RSC","0203 Full overlap","0427 Die-cut","Custom"]],["Internal Dimensions","text","L × W × H (mm)"],["Ply / Flute","select",["3 Ply B","3 Ply E","5 Ply BC","7 Ply"]],["Paper Combination","text","Kraft 180 / Medium 120 / Kraft 180"],["GSM / BF","text","180 GSM / 22 BF"],["Print Colors","number","2"],["Die / Plate","text","Tool reference"],["Board Area","number","1.25"],["Order Quantity","number","10000"],["Bundle Size","number","20"],["Target Waste %","number","4.0"]],
  finance:[["Ledger / Account","select",["Raw Material","Production Cost","Sales Revenue","GST Input","GST Output"]],["Cost Center","select",["Textile Plant","Carton Plant","Corporate"]],["Currency","select",["INR","USD","EUR"]],["Debit Amount","number","0"],["Credit Amount","number","0"],["Tax Code","select",["GST 5%","GST 12%","GST 18%","Exempt"]],["Payment Terms","select",["Advance","Net 30","Net 45","Net 60"]],["Due Date","date",""]],
  quality:[["Inspection Type","select",["Incoming","In Process","Final","Audit"]],["Specification","text","Applicable standard"],["Characteristic","text","Measurement / defect"],["Lower Limit","number","0"],["Upper Limit","number","100"],["Sample Size","number","5"],["Instrument","text","Instrument ID"],["Result","select",["Pass","Fail","Conditional"]],["Disposition","select",["Release","Hold","Rework","Reject"]]],
  default:[["Business Partner","text","Customer / supplier / department"],["Item / Service","text","Search code or description"],["Quantity","number","100"],["UoM","select",["Each","Kg","Meter","Square Meter","Roll"]],["Required Date","date",""],["Warehouse / Location","select",["RM Store","WIP Store","FG Store","Quality Hold"]],["Amount / Value","number","0"],["Approval Rule","select",["Standard","High Value","Urgent"]]]
};

function fieldType(){const t=(domains[currentGroup]?.[0]+" "+domains[currentGroup]?.[1]?.[currentPage]?.[0]).toLowerCase();if(/gate|security|visitor|vehicle|weighbridge|yard|dock|access/.test(t))return"gate";if(/employee|attendance|shift roster|payroll|manpower|recruitment|leave|overtime|payslip|appraisal|separation/.test(t))return"people";if(/textile|yarn|fabric|weav|dye|style|sewing|shade/.test(t))return"textile";if(/carton|corrugat|board|box|paper|die |plate|trim/.test(t))return"carton";if(/finance|ledger|account|bank|tax|cost|invoice|budget|cash|payment|receipt|journal/.test(t))return"finance";if(/quality|inspection|capa|nonconform|calibration|complaint|audit/.test(t))return"quality";return"default"}
function activeSchema(){const [group,mods]=domains[currentGroup],m=mods[currentPage];return window.PRODX_SCHEMA(group,m[0],m[1])}
function renderNav(filter=""){$("mainNav").innerHTML="";domains.forEach((d,gi)=>{const matches=d[0].toLowerCase().includes(filter)||d[1].some(m=>m[0].toLowerCase().includes(filter));if(!matches)return;const group=document.createElement("div");group.className="nav-group"+(gi===currentGroup?" open":"");const main=document.createElement("button");main.className="nav-main"+(gi===currentGroup?" active":"");main.innerHTML=`<span class="icon">${icons[gi]||"•"}</span><span class="label">${d[0]}</span><span class="count">${d[1].length}</span><span class="arrow">›</span>`;main.onclick=()=>{if(group.classList.contains("open"))group.classList.remove("open");else{document.querySelectorAll(".nav-group").forEach(x=>x.classList.remove("open"));group.classList.add("open")}};const sub=document.createElement("div");sub.className="nav-sub";d[1].forEach((m,mi)=>{if(filter&&!m[0].toLowerCase().includes(filter)&&!d[0].toLowerCase().includes(filter))return;const b=document.createElement("button");b.textContent=m[0];b.className=gi===currentGroup&&mi===currentPage?"active":"";b.onclick=()=>selectPage(gi,mi);sub.appendChild(b)});group.append(main,sub);$("mainNav").appendChild(group)})}
function selectPage(gi,mi){currentGroup=gi;currentPage=mi;renderNav($("menuSearch").value.toLowerCase());renderPage();document.querySelector(".sidebar").classList.remove("open");$("mobileOverlay").classList.remove("show")}
function renderPage(){const [group,mods]=domains[currentGroup],mod=mods[currentPage];$("pageGroup").textContent=group.toUpperCase();$("pageTitle").textContent=mod[0];$("pageDescription").textContent=mod[1];$("breadcrumbs").textContent=`${group} / ${mod[0]}`;renderHeadActions();renderMetrics(mod[0]);renderGrid(mod[0]);renderForm();renderDetail();renderApproval();renderControls();renderAudit();switchView(currentView)}
function renderHeadActions(){const s=activeSchema();$("headActions").innerHTML=`<button class="btn secondary page-action">Export</button>${s.actions.slice(0,3).map(a=>`<button class="btn ${a===s.primaryAction?"primary":"secondary"} page-action">${a}</button>`).join("")}`;document.querySelectorAll(".page-action").forEach((b,i)=>b.onclick=()=>i===1?switchView("form"):showToast())}
function renderMetrics(name){const type=fieldType(),sets={finance:[["Open Value","₹ 48.2L","₹ 9.6L due"],["Pending Posting","12","3 urgent"],["Reconciled Today","42","96% matched"],["Exceptions","4","1 resolved"]],gate:[["Vehicles Inside","18","6 unloading"],["Pending Gate Out","7","2 on hold"],["Avg. Turnaround","86 min","↓ 12 min"],["Security Alerts","3","1 critical"]],people:[["People on Shift","486","92% present"],["Access Exceptions","6","2 expired skills"],["Payroll Inputs","24","Awaiting approval"],["Training Due","19","7 this week"]],quality:[["Lots on Hold","14","₹ 6.8L value"],["Inspections Due","28","9 urgent"],["First-pass Yield","96.4%","↑ 1.2%"],["Open CAPA","8","2 overdue"]]};const labels=sets[type]||[["Open Records","128","↑ 12%"],["Pending Approval","8","3 urgent"],["Completed Today","42","↑ 7%"],["Exceptions","5","↓ 2 today"]];$("metricGrid").innerHTML=labels.map((m,i)=>`<div class="metric"><span class="metric-icon">${["▤","✓","◆","!"][i]}</span><div><small>${m[0]}</small><b>${m[1]}</b><small class="trend">${m[2]}</small></div></div>`).join("")}
function columns(){return activeSchema().grid}
function sampleValue(label,i){const l=label.toLowerCase(),title=domains[currentGroup][1][currentPage][0];if(/status|decision|result|disposition|lifecycle|condition|compliance/.test(l))return["Open","Pending","Approved","Hold","Closed"][i%5];if(/date|time|period/.test(l))return`${String((i%9)+1).padStart(2,"0")} Aug 2026`;if(/customer|party/.test(l))return["Apex Retail","Metro Export","Nova Brands","Prime Packaging"][i%4];if(/supplier|vendor/.test(l))return["Kraft Paper Co.","Shakti Yarns","Reliable Chemicals","Industrial Services"][i%4];if(/plant|site|location|warehouse/.test(l))return["Plant 01","Textile Store","Carton Plant","Quality Hold"][i%4];if(/machine|resource|loom|line|asset/.test(l))return["Machine 01","Loom 12","Corrugator 1","Line 03"][i%4];if(/owner|buyer|planner|operator|inspector|technician|user/.test(l))return["A. Shah","R. Kumar","S. Patel","M. Khan"][i%4];if(/quantity|count|meters|weight|output|sample|capacity/.test(l))return((i+2)*250).toLocaleString("en-IN");if(/amount|value|cost|price|debit|credit|balance|rate/.test(l))return`₹ ${((i+2)*1.24).toFixed(2)}L`;if(/%|efficiency|yield|margin|waste|moisture|confidence|oee/.test(l))return`${82+i%12}.${i}%`;if(/lot|batch|roll|beam|pallet/.test(l))return`LOT-${currentGroup+1}${currentPage+1}${170+i}`;if(/item|material|product|style|fabric|box|board|yarn/.test(l))return fieldType()==="carton"?["5 Ply Export Box","3 Ply RSC","Kraft Liner 180","Die-cut Mailer"][i%4]:fieldType()==="textile"?["Cotton Poplin 40s","Jersey 180 GSM","Dyed Fabric Navy","Cotton Yarn 40s"][i%4]:["RM-001","FG-240","Service Item","Component A"][i%4];if(/description|name|purpose|requirement|reference/.test(l))return`${title} ${["Standard","Priority","Revision B","Plant 01"][i%4]}`;if(/target|actual|achieved|variance|deviation|budget/.test(l)){const t=(i+2)*500,d=((i*37+60)%190)*(i%2?1:-1);if(/variance|deviation/.test(l))return`${d>0?"+":""}${(d/t*100).toFixed(1)}%`;return(/target|budget/.test(l)?t:t+d).toLocaleString("en-IN")}return["Standard","Revision B","Normal","Verified"][i%4]}
function rowData(i){const s=activeSchema(),cols=columns(),id=`${s.prefix}-${String(2400+i).padStart(5,"0")}`;return cols.map((c,ci)=>ci===0?id:ci===cols.length-1?s.workflow[i%s.workflow.length]:sampleValue(c,i))}
function renderGrid(){const cols=columns();$("gridHead").innerHTML=`<tr><th><input type="checkbox" aria-label="Select all"></th>${cols.map(c=>`<th>${c}</th>`).join("")}<th>Actions</th></tr>`;const rows=Array.from({length:10},(_,i)=>rowData(i));$("gridBody").innerHTML=rows.map(r=>`<tr><td><input type="checkbox" aria-label="Select record"></td>${r.map((v,i)=>i===0?`<td class="row-id">${v}</td>`:i===r.length-1?`<td><span class="chip ${String(v).toLowerCase()}">${v}</span></td>`:`<td>${v}</td>`).join("")}<td><button class="row-action" title="Open">•••</button></td></tr>`).join("");$("resultCount").textContent=`Showing 1–10 of ${128+currentPage*7} records`}
function createField(f,i){const [label,type,data]=f,id=`field-${currentGroup}-${currentPage}-${i}`;let control;if(type==="select")control=`<select id="${id}">${data.map(x=>`<option>${x}</option>`).join("")}</select>`;else if(type==="textarea")control=`<textarea id="${id}" placeholder="${data||""}"></textarea>`;else control=`<input id="${id}" type="${type}" placeholder="${data||""}" ${type==="date"?`value="2026-08-06"`:""}>`;return`<div class="field ${type==="textarea"?"full":""}"><label class="${i<4?"required":""}" for="${id}">${label}</label>${control}</div>`}
function renderForm(){const schema=activeSchema(),m=domains[currentGroup][1][currentPage];$("technicalTitle").textContent=`${m[0]} — Module Fields`;$("basicFields").innerHTML=commonFields.slice(0,6).map(createField).join("");$("technicalFields").innerHTML=schema.fields.map(createField).join("");$("lineSectionTitle").textContent=schema.lineTitle;$("formWorkflow").innerHTML=schema.workflow.map((w,i)=>`<li class="${i===0?"done":i===1?"current":""}"><span>${i===0?"✓":i+1}</span><div><b>${w}</b><small>${i===0?"Record initialized":i===1?"Current working stage":"Controlled next step"}</small></div></li>`).join("");lineNo=3;renderLines()}
function renderLines(){const schema=activeSchema(),cols=schema.lineColumns;$("lineHead").innerHTML=`<tr><th>#</th>${cols.map(c=>`<th>${c}</th>`).join("")}<th></th></tr>`;$("lineItems").innerHTML=Array.from({length:lineNo},(_,i)=>`<tr><td>${i+1}</td>${cols.map((c,ci)=>{const v=sampleValue(c,i);return`<td><input ${/quantity|rate|amount|cost/.test(c.toLowerCase())?`type="number" value="${(i+1)*(ci+2)*25}"`:`value="${v}"`}></td>`}).join("")}<td><button type="button" class="remove-line" data-line="${i}">×</button></td></tr>`).join("");document.querySelectorAll(".remove-line").forEach(b=>b.onclick=()=>{if(lineNo>1){lineNo--;renderLines()}})}
function renderDetail(){const mod=domains[currentGroup][1][currentPage],r=rowData(0),defs=columns().slice(1,7).map((c,i)=>[c,r[i+1]]);$("detailContent").innerHTML=`<div class="panel detail-hero"><div class="detail-code">${String(currentGroup+1).padStart(2,"0")}</div><div><h2>${r[0]} • ${mod[0]}</h2><p>${mod[1]}</p></div><span class="chip approved">Approved</span><button class="btn secondary">Edit</button><button class="btn secondary">Print</button></div><div class="detail-grid"><div><div class="panel"><div class="section-title" style="padding:16px;margin:0"><div><h2>Record Information</h2><p>Current approved values</p></div></div><div class="definition-grid">${defs.map(x=>`<div class="definition"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}</div></div><div class="panel" style="margin-top:16px"><div class="section-title" style="padding:16px;margin:0"><div><h2>Lines & Transactions</h2><p>Materials, operations and financial impact</p></div></div><div class="table-wrap"><table><thead>${$("gridHead").innerHTML}</thead><tbody>${$("gridBody").innerHTML.split("</tr>").slice(0,3).join("</tr>")}</tbody></table></div></div></div><div><div class="panel side-card"><h3>Current status</h3><ol class="stepper"><li class="done"><span>✓</span><div><b>Created</b><small>06 Aug • Admin User</small></div></li><li class="done"><span>✓</span><div><b>Validated</b><small>All policy checks passed</small></div></li><li class="done"><span>✓</span><div><b>Approved</b><small>Plant Head</small></div></li><li class="current"><span>4</span><div><b>In execution</b><small>Operational processing</small></div></li></ol></div><div class="panel side-card" style="margin-top:16px"><h3>Linked documents</h3><ul class="check-list"><li>▣ Specification_v3.pdf</li><li>▣ Approval_note.pdf</li><li>▣ Cost_sheet.xlsx</li></ul></div></div></div>`}
function renderApproval(){const mod=domains[currentGroup][1][currentPage];$("approvalContent").innerHTML=`<div class="approval-layout"><div><div class="panel approval-banner"><div class="alert-icon">!</div><div><h2>${mod[0]} awaiting your approval</h2><p>Review master data, values, attachments and control checks before taking action.</p><textarea class="comment-box" placeholder="Add approval comment or rejection reason..."></textarea><div class="approval-actions"><button class="btn danger action-toast">Reject</button><button class="btn secondary action-toast">Return for correction</button><button class="btn primary action-toast">Approve</button></div></div></div><div class="panel" style="margin-top:16px;padding:18px"><h3>Approval checklist</h3><div class="definition-grid"><div class="definition"><small>Budget / Value</small><b>Within approved limit</b></div><div class="definition"><small>Master data</small><b>Validated</b></div><div class="definition"><small>Documents</small><b>3 attached</b></div><div class="definition"><small>Policy exceptions</small><b>None</b></div><div class="definition"><small>Previous approver</small><b>Department Head</b></div><div class="definition"><small>Due by</small><b>Today, 5:00 PM</b></div></div></div></div><aside class="panel side-card"><h3>Approval route</h3><ol class="stepper"><li class="done"><span>✓</span><div><b>Creator</b><small>Admin User</small></div></li><li class="done"><span>✓</span><div><b>Department Head</b><small>Approved • 10:42</small></div></li><li class="current"><span>3</span><div><b>Plant Head</b><small>Current step</small></div></li><li><span>4</span><div><b>Finance / Final</b><small>If threshold applies</small></div></li></ol></aside></div>`;document.querySelectorAll(".action-toast").forEach(x=>x.onclick=showToast)}
function renderAudit(){$("auditContent").innerHTML=`<div class="panel"><div class="section-title" style="padding:16px;margin:0"><div><h2>Immutable audit trail</h2><p>Who changed what, when, why and from which source.</p></div><button class="btn secondary small">⇩ Export Audit</button></div><div class="table-wrap"><table class="audit-table"><thead><tr><th>Date & Time</th><th>Action</th><th>User</th><th>Before</th><th>After</th><th>Reason / Source</th></tr></thead><tbody><tr><td>06 Aug 2026 • 11:22</td><td>Approved</td><td>Plant Head</td><td>Pending</td><td>Approved</td><td>Web • Policy AP-04</td></tr><tr><td>06 Aug 2026 • 10:42</td><td>Submitted</td><td>Admin User</td><td>Draft</td><td>Pending</td><td>Web • User action</td></tr><tr><td>06 Aug 2026 • 10:38</td><td>Quantity changed</td><td>Admin User</td><td>4,500</td><td>5,000</td><td>Customer revision CR-02</td></tr><tr><td>06 Aug 2026 • 10:31</td><td>Attachment added</td><td>Admin User</td><td>—</td><td>Specification_v3.pdf</td><td>Web upload</td></tr><tr><td>06 Aug 2026 • 10:25</td><td>Created</td><td>Admin User</td><td>—</td><td>Draft record</td><td>Web • Manual entry</td></tr></tbody></table></div></div>`}
function infoCard(title,items,kind=""){return`<article class="panel control-card ${kind}"><h3>${title}</h3><ul>${items.map(x=>`<li><span>✓</span><div>${x}</div></li>`).join("")}</ul></article>`}
function renderControls(){const s=activeSchema(),m=domains[currentGroup][1][currentPage];$("controlsContent").innerHTML=`<div class="panel control-hero"><div><span class="eyebrow">CONTROL DESIGN • ${s.prefix}</span><h2>${m[0]} operating model</h2><p>How this transaction moves, what is validated, and which downstream ledgers or systems are affected.</p></div><button class="btn primary page-action">${s.primaryAction}</button></div><div class="lifecycle">${s.workflow.map((w,i)=>`<div class="life-step"><b>${i+1}</b><span>${w}</span></div>`).join("")}</div><div class="controls-grid">${infoCard("Mandatory validations",s.validations,"validation")}${infoCard("Posting & business impact",s.impacts,"impact")}${infoCard("System integrations",s.integrations,"integration")}${infoCard("Standard reports",s.reports,"report")}</div><div class="panel governance"><h3>Exception and governance rules</h3><div class="definition-grid"><div class="definition"><small>Record identity</small><b>${s.prefix}-YYYY-NNNNN</b></div><div class="definition"><small>Deletion policy</small><b>Posted records cannot be deleted</b></div><div class="definition"><small>Correction policy</small><b>Reverse, reference and repost</b></div><div class="definition"><small>Approval evidence</small><b>User, time, comment and policy retained</b></div><div class="definition"><small>Access control</small><b>Role + plant + value authority</b></div><div class="definition"><small>Audit retention</small><b>Configurable legal retention</b></div></div></div>`;$("controlsContent").querySelector(".page-action").onclick=showToast}
function switchView(v){currentView=v;document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(`${v}View`).classList.add("active")}
function showToast(){$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>switchView(t.dataset.view));$("menuSearch").oninput=e=>renderNav(e.target.value.toLowerCase());$("recordSearch").oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("#gridBody tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?"":"none")};$("addLine").onclick=()=>{lineNo++;renderLines()};$("recordForm").onsubmit=e=>{e.preventDefault();showToast();switchView("detail")};$("saveDraft").onclick=showToast;$("newBtn").onclick=()=>switchView("form");$("exportBtn").onclick=showToast;$("menuOpen").onclick=()=>{$("sidebar").classList.add("open");$("mobileOverlay").classList.add("show")};$("menuClose").onclick=$("mobileOverlay").onclick=()=>{$("sidebar").classList.remove("open");$("mobileOverlay").classList.remove("show")};
renderNav();renderPage();
