(function(){
const journeys=[
 {name:"Order to Cash",owner:"Sales + Production + Finance",stages:["Product Enquiry","Cost Estimate","Quotation","Sales Order","MRP","Work Order","Production Confirmation","Board & Box Quality","Dispatch & Shipment","Accounts Receivable","Customer Receipt","Job / Order Profitability"]},
 {name:"Procure to Pay",owner:"Purchase + Gate + Stores + Accounts",stages:["Purchase Requisition","RFQ & Bid Comparison","Purchase Order","Vehicle Pre-Advice","Gate In Entry","Weighbridge Transaction","Goods Receipt","Supplier Quality","Supplier Invoice Register","Invoice OCR & 3-Way Match","Supplier Payment","Gate Out Entry"]},
 {name:"Gate & Logistics",owner:"Security + Warehouse",stages:["Vehicle Pre-Advice","Gate In Entry","Inward Gate Pass","Weighbridge Transaction","Dock & Yard Management","Goods Receipt","Outward Gate Pass","Dispatch & Shipment","Gate Out Entry","Returnable Material Register"]},
 {name:"Plan to Produce",owner:"Planning + Shop Floor + Quality",stages:["Forecast & Demand Plan","MRP","Capacity Planning","Finite Scheduler","Material Allocation","Work Order","Material Staging","Operation Start / Stop","Production Confirmation","WIP Tracking","Final Inspection","Packing & Labeling"]},
 {name:"Hire to Payroll",owner:"HR + Security + Finance",stages:["Manpower Requisition","Recruitment & Joining","Employee / Contractor Master","Training","Attendance & Shift Roster","Employee / Contractor Access","Overtime & Incentive","Payroll Processing","Payslip & Bank Transfer","Separation & Full-and-Final"]},
 {name:"Record to Report",owner:"Accounts + Plant Management",stages:["Budget & Cash Forecast","Supplier Invoice Register","Accounts Payable","Supplier Payment","Accounts Receivable","Customer Receipt","Cash & Bank","Journal Voucher","Standard & Actual Cost","Period Close & Reconciliation","General Ledger","Job / Order Profitability"]}
];
const roleMap={"Security Officer":["Gate, Security & Weighbridge"],"Sales Manager":["CRM, Costing & Sales"],"Purchase Manager":["Procurement & Supplier"],"Store Executive":["Inventory, Warehouse & Logistics"],"Production Supervisor":["Shared Manufacturing & MES","Textile & Garment Manufacturing","Corrugated Carton Manufacturing"],"Quality Inspector":["Quality Management"],"HR Manager":["People, Safety & Sustainability"],"Accountant":["Finance, Cost & Compliance"],"Plant Head":[]};
let selected=0;
function locate(title){for(let gi=0;gi<domains.length;gi++){const mi=domains[gi][1].findIndex(x=>x[0]===title);if(mi>=0)return[gi,mi]}return null}
function state(){return JSON.parse(localStorage.getItem("prodxJourney")||"{}")}
function saveState(v){localStorage.setItem("prodxJourney",JSON.stringify(v))}
function render(){const j=journeys[selected],st=state(),done=st[j.name]||0,role=$("roleSelect").value;$("journeyContent").innerHTML=`<div class="journey-head panel"><div><span class="eyebrow">CONNECTED BUSINESS DEMO</span><h2>${j.name}</h2><p>${j.owner} • Signed in as ${role}</p></div><div class="journey-actions"><button class="btn secondary" id="resetJourney">Reset</button><button class="btn primary" id="advanceJourney">Advance Demo</button></div></div><div class="journey-picker">${journeys.map((x,i)=>`<button class="${i===selected?"active":""}" data-j="${i}">${x.name}</button>`).join("")}</div><div class="process-track">${j.stages.map((x,i)=>`<button class="process-step ${i<done?"done":i===done?"current":""}" data-stage="${x}"><span>${i<done?"✓":i+1}</span><b>${x}</b><small>${i<done?"Completed":i===done?"Current activity":"Pending"}</small></button>`).join("")}</div><div class="journey-summary"><article class="panel"><h3>Linked transaction</h3><p><b>${j.name.slice(0,3).toUpperCase()}-2026-00418</b></p><small>Every stage retains the same business reference and linked documents.</small></article><article class="panel"><h3>Current responsibility</h3><p><b>${j.stages[Math.min(done,j.stages.length-1)]}</b></p><small>Role, approval and plant authority are checked before action.</small></article><article class="panel"><h3>Control status</h3><p><b>${done}/${j.stages.length} completed</b></p><small>Exceptions, reversals and audit events remain traceable.</small></article></div>`;
document.querySelectorAll("[data-j]").forEach(b=>b.onclick=()=>{selected=+b.dataset.j;render()});document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>{const at=locate(b.dataset.stage);if(at){selectPage(at[0],at[1]);switchView("form")}else showToast()});
$("advanceJourney").onclick=()=>{const s=state();s[j.name]=Math.min((s[j.name]||0)+1,j.stages.length);saveState(s);render();showToast()};$("resetJourney").onclick=()=>{const s=state();s[j.name]=0;saveState(s);render()};}
document.querySelector('[data-view="journey"]').onclick=()=>{switchView("journey");render()};$("roleSelect").onchange=()=>{localStorage.setItem("prodxRole",$("roleSelect").value);render();const allowed=roleMap[$("roleSelect").value];document.querySelectorAll(".nav-group").forEach((g,i)=>g.classList.toggle("role-muted",allowed.length&&!allowed.includes(domains[i][0])))};$("roleSelect").value=localStorage.getItem("prodxRole")||"Plant Head";
const oldSubmit=$("recordForm").onsubmit;$("recordForm").onsubmit=e=>{e.preventDefault();const missing=[...$("recordForm").querySelectorAll("label.required")].map(l=>document.getElementById(l.htmlFor)).filter(x=>x&&!String(x.value).trim());if(missing.length){missing.forEach(x=>x.classList.add("invalid"));$("toast").querySelector("b").textContent="Complete required fields";$("toast").querySelector("small").textContent=`${missing.length} mandatory values are missing.`;showToast();return}oldSubmit?.(e)};
window.addEventListener("keydown",e=>{if(e.ctrlKey&&e.key.toLowerCase()==="p"){e.preventDefault();window.print()}});render();
})();
