(function(){
const T=(label,type="text",data="")=>[label,type,data];
const S=(...x)=>T(x.shift(),"select",x);
const exact={
"Item & Material Master":[T("Item Code"),T("Item Description"),S("Item Type","Raw Material","WIP","Finished Good","Service","Consumable"),T("Base UoM"),T("Material Group"),T("HSN / SAC"),T("Shelf Life (Days)","number"),S("Lot Control","None","Lot","Batch","Serial","Roll"),S("Valuation Method","Standard","Moving Average","FIFO"),T("Standard Cost","number"),S("Quality Inspection","Required","Optional","Not Required"),T("Approved Specification")],
"Customer & Supplier Master":[T("Party Code"),S("Party Type","Customer","Supplier","Both"),T("Legal Name"),T("GSTIN / Tax ID"),T("PAN / Registration"),T("Credit Limit","number"),S("Payment Terms","Advance","Net 30","Net 45","Net 60"),T("Default Currency"),T("Quality Rating","number"),T("Lead Time (Days)","number"),T("Primary Contact"),T("Registered Address","textarea")],
"BOM / Recipe / Routing":[T("Product / Formula"),T("Revision"),T("Effective From","date"),S("Structure Type","BOM","Recipe","Routing","Combined"),T("Base Quantity","number"),T("Yield %","number"),T("Scrap %","number"),T("Default Plant"),T("Alternate Method"),S("Approval Status","Draft","Under Review","Released","Obsolete")],
"Cost Estimate":[T("Estimate Number"),T("Customer / Prospect"),T("Product / Specification"),T("Order Quantity","number"),T("Material Cost","number"),T("Machine Cost","number"),T("Labor Cost","number"),T("Waste %","number"),T("Tooling Cost","number"),T("Freight","number"),T("Overhead %","number"),T("Target Margin %","number"),T("Quoted Price","number")],
"Quotation":[T("Quote Number"),T("Customer"),T("Enquiry Reference"),T("Product / Specification"),T("Quantity","number"),T("Unit Price","number"),T("Tax Code"),T("Delivery Lead Time"),T("Validity Date","date"),T("Payment Terms"),T("Freight Terms"),T("Margin %","number"),S("Approval Status","Draft","Margin Approval","Approved","Sent","Accepted","Rejected")],
"Sales Order":[T("Sales Order Number"),T("Customer"),T("Customer PO Number"),T("PO Date","date"),T("Product / Specification"),T("Order Quantity","number"),T("UoM"),T("Unit Price","number"),T("Requested Delivery","date"),T("Committed Delivery","date"),T("Ship-to Location"),T("Credit Status"),S("Order Status","Draft","Confirmed","Planned","In Production","Dispatched","Closed")],
"Forecast & Demand Plan":[T("Forecast Version"),T("Planning Horizon"),T("Customer / Market"),T("Product Family"),T("Baseline Forecast","number"),T("Sales Override","number"),T("Final Forecast","number"),T("Confidence %","number"),T("Season / Campaign"),T("Forecast UoM"),S("Approval Status","Working","Consensus","Approved","Frozen")],
"MRP":[T("Planning Run ID"),T("Plant"),T("Planning Date","date"),T("Horizon End","date"),S("Scope","All Materials","Selected Group","Selected Orders"),S("Netting Rule","Net Change","Regenerative"),T("Safety Stock Rule"),T("Lead-time Rule"),T("Planned Orders","number"),T("Purchase Proposals","number"),T("Exception Count","number")],
"Finite Scheduler":[T("Schedule Version"),T("Plant / Area"),T("Schedule Start","datetime-local"),T("Schedule End","datetime-local"),T("Constraint Set"),T("Priority Rule"),T("Changeover Matrix"),T("Frozen Horizon (Hours)","number"),T("Late Orders","number"),T("Average Utilization %","number"),S("Status","Draft","Optimized","Released","Superseded")],
"Purchase Requisition":[T("PR Number"),T("Requesting Department"),T("Requester"),T("Requirement Date","date"),T("Material / Service"),T("Quantity","number"),T("UoM"),T("Estimated Rate","number"),T("Preferred Supplier"),T("Cost Center"),T("Budget Reference"),T("Justification","textarea"),S("Status","Draft","Submitted","Approved","Converted","Closed")],
"RFQ & Bid Comparison":[T("RFQ Number"),T("PR Reference"),T("Material / Service"),T("Required Quantity","number"),T("Bid Due Date","date"),T("Invited Suppliers","number"),T("Received Bids","number"),T("Lowest Landed Price","number"),T("Best Lead Time (Days)","number"),T("Quality Weight %","number"),T("Commercial Weight %","number"),T("Recommended Supplier")],
"Purchase Order":[T("PO Number"),T("Supplier"),T("Supplier Quote"),T("Order Date","date"),T("Material / Service"),T("Quantity","number"),T("UoM"),T("Unit Price","number"),T("Tax Code"),T("Delivery Date","date"),T("Ship-to Plant"),T("Payment Terms"),T("Incoterm / Freight"),S("Status","Draft","Approval","Released","Acknowledged","Part Received","Closed")],
"Subcontracting":[T("Subcontract Order"),T("Vendor"),T("Outside Operation"),T("Parent Work Order"),T("Material Sent"),T("Sent Quantity","number"),T("Expected Yield %","number"),T("Expected Return Date","date"),T("Processing Rate","number"),T("Allowed Loss %","number"),T("Actual Receipt","number"),T("Vendor Stock Balance","number")],
"Goods Receipt":[T("GRN Number"),T("PO / ASN Reference"),T("Supplier"),T("Receipt Date","date"),T("Material"),T("Supplier Lot / Roll"),T("Received Quantity","number"),T("Accepted Quantity","number"),T("Rejected Quantity","number"),T("Warehouse / Dock"),T("Vehicle Number"),S("Inspection Status","Pending","Passed","Failed","Conditional")],
"Invoice OCR & 3-Way Match":[T("Invoice Number"),T("Supplier"),T("Invoice Date","date"),T("Invoice Amount","number"),T("PO Reference"),T("GRN Reference"),T("OCR Confidence %","number"),T("PO Variance","number"),T("Receipt Variance","number"),T("Tax Variance","number"),S("Match Status","Matched","Within Tolerance","Exception","Duplicate Suspected"),T("Exception Owner")],
"Lot / Roll / Batch Traceability":[T("Trace ID"),T("Material / Product"),S("Trace Unit","Lot","Batch","Roll","Serial","Pallet"),T("Supplier / Source Lot"),T("Internal Lot"),T("Work Order"),T("Operation / Machine"),T("Current Location"),T("Quantity","number"),T("Quality Status"),T("Customer Shipment"),T("Parent / Child Genealogy")],
"Cycle Count & Stock Take":[T("Count Document"),T("Warehouse / Zone"),T("Count Date","date"),S("Count Type","Cycle","Annual","Spot","Blind"),T("Count Team"),T("Items Planned","number"),T("Items Counted","number"),T("Variance Items","number"),T("Book Value","number"),T("Variance Value","number"),S("Status","Planned","Counting","Recount","Approved","Posted")],
"Dispatch & Shipment":[T("Shipment Number"),T("Customer / Destination"),T("Sales Orders"),T("Dispatch Date","date"),T("Transporter"),T("Vehicle Number"),T("Driver / Contact"),T("Package / Pallet Count","number"),T("Gross Weight","number"),T("E-Way Bill"),T("LR / Tracking Number"),S("POD Status","Pending","In Transit","Delivered","Exception")],
"RFID / Barcode Control":[T("Device / Reader ID"),S("Technology","Barcode","QR","RFID UHF","RFID HF"),T("Reader Location"),T("Tag / Label Template"),T("Entity Type"),T("Entity Identifier"),T("Last Scan Time","datetime-local"),T("Signal / Read Count","number"),T("Expected Event"),T("Actual Event"),S("Validation","Valid","Duplicate","Out of Sequence","Unknown Tag")],
"Work Order":[T("Work Order Number"),T("Product"),T("Production Version"),T("Order Quantity","number"),T("UoM"),T("Planned Start","datetime-local"),T("Planned Finish","datetime-local"),T("Routing"),T("BOM / Recipe Revision"),T("Priority"),T("Planner"),T("Sales Order / Demand"),S("Status","Created","Released","In Process","Hold","Completed","Closed")],
"Operation Start / Stop":[T("Execution ID"),T("Work Order"),T("Operation"),T("Machine / Resource"),T("Operator"),T("Shift"),T("Start Time","datetime-local"),T("Stop Time","datetime-local"),T("Good Quantity","number"),T("Scrap Quantity","number"),T("Downtime Reason"),T("Electronic Sign-off")],
"Machine Data / OEE":[T("Machine"),T("Date / Shift"),T("Planned Production Time","number"),T("Run Time","number"),T("Ideal Cycle Time","number"),T("Total Count","number"),T("Good Count","number"),T("Availability %","number"),T("Performance %","number"),T("Quality %","number"),T("OEE %","number"),T("Top Loss Reason")],
"Style / Color / Size Matrix":[T("Style Code"),T("Style Name"),T("Season / Collection"),T("Division / Brand"),T("Base Fabric"),T("Colorway"),T("Size Range"),T("Width / Fit"),T("SKU Count","number"),T("Sample Status"),T("Costing Version"),S("Lifecycle","Concept","Development","Approved","Active","Discontinued")],
"Yarn & Fiber Master":[T("Yarn Code"),T("Fiber Composition"),T("Count System"),T("Yarn Count"),T("Blend %"),T("Twist / TPM"),T("Ply"),T("Color / Shade"),T("Cone Weight","number"),T("Supplier / Mill"),T("Certificate / Origin"),T("Approved Quality Grade")],
"Fabric Specification":[T("Fabric Code"),T("Construction / Knit"),T("Warp Count"),T("Weft Count"),T("Ends / Picks"),T("Target GSM","number"),T("Finished Width"),T("Composition"),T("Finish"),T("Shrinkage Warp %","number"),T("Shrinkage Weft %","number"),T("Color Fastness Grade")],
"Warping & Sizing Plan":[T("Plan / Beam Number"),T("Fabric / Style"),T("Warp Yarn"),T("Total Ends","number"),T("Beam Length","number"),T("Number of Beams","number"),T("Sizing Recipe"),T("Size Pick-up %","number"),T("Warper / Sizer"),T("Planned Start","datetime-local"),T("Expected Waste %","number"),T("Beam Status")],
"Weaving / Knitting Execution":[T("Execution Number"),T("Work Order"),T("Loom / Knitting Machine"),T("Beam / Yarn Lot"),T("Fabric Construction"),T("Target Meters / Kg","number"),T("Actual Output","number"),T("Picks / RPM","number"),T("Loom Efficiency %","number"),T("Defect Points","number"),T("Operator / Weaver"),T("Shift")],
"Dyeing Batch & Recipe":[T("Dye Batch Number"),T("Fabric / Yarn Lot"),T("Shade / Color Standard"),T("Batch Weight (Kg)","number"),T("Machine"),T("Machine Capacity","number"),T("Liquor Ratio"),T("Recipe Version"),T("Dyes & Chemicals Cost","number"),T("Process Start","datetime-local"),T("Lab Result / Delta E","number"),S("Shade Status","Pending","Pass","Correction","Re-dye")],
"Finishing & Stenter":[T("Finish Batch"),T("Input Fabric Lot"),T("Finish Type"),T("Stenter Machine"),T("Input Width"),T("Target Width"),T("Input GSM","number"),T("Target GSM","number"),T("Speed (m/min)","number"),T("Temperature °C","number"),T("Overfeed %","number"),T("Actual Shrinkage %","number")],
"Fabric Inspection & Grading":[T("Inspection Number"),T("Fabric Roll"),T("Work Order / Batch"),T("Inspected Meters","number"),T("Defect Count","number"),T("4-Point Score","number"),T("Points / 100 SqM","number"),T("Cuttable Width"),T("Shade Group"),S("Grade","A","B","C","Reject"),T("Inspector"),S("Disposition","Release","Hold","Rework","Reject")],
"Shade / Lab Dip Approval":[T("Submission Number"),T("Customer"),T("Color Standard"),T("Pantone / Reference"),T("Lab Dip Version"),T("Recipe Reference"),T("Spectro Delta E","number"),T("Submission Date","date"),T("Customer Response Date","date"),S("Decision","Pending","Approved","Rejected","Resubmit"),T("Approved Standard Location")],
"Cut Plan & Marker":[T("Cut Plan Number"),T("Style / Order"),T("Fabric / Shade"),T("Marker Number"),T("Marker Width"),T("Marker Length"),T("Marker Efficiency %","number"),T("Ply Count","number"),T("Planned Pieces","number"),T("Fabric Allocated","number"),T("Expected Remnant","number"),T("Cutting Table")],
"Sewing Line Control":[T("Line Plan"),T("Style / Order"),T("Sewing Line"),T("Operation Bulletin"),T("SAM Minutes","number"),T("Manpower","number"),T("Hourly Target","number"),T("Hourly Output","number"),T("Line WIP","number"),T("Efficiency %","number"),T("DHU %","number"),T("Bottleneck Operation")],
"Board / Paper Specification":[T("Paper / Board Code"),S("Material Type","Kraft Liner","Test Liner","Fluting Medium","Duplex Board","Coated Board"),T("GSM","number"),T("Burst Factor","number"),T("RCT / SCT"),T("Moisture %","number"),T("Reel Width (mm)","number"),T("Reel Diameter (mm)","number"),T("Core Diameter"),T("Supplier / Mill"),T("Shade / Finish"),T("Approved Standard")],
"Box Design & FEFCO Style":[T("Box Design Code"),T("Customer"),T("FEFCO Style"),T("Internal Length (mm)","number"),T("Internal Width (mm)","number"),T("Internal Height (mm)","number"),S("Ply","3 Ply","5 Ply","7 Ply"),S("Flute","E","B","C","BC","EB"),T("Joint / Closure"),T("Board Combination"),T("Drawing Revision"),T("Tolerance")],
"Artwork & Prepress":[T("Artwork Number"),T("Customer / Brand"),T("Box / Product"),T("Artwork Revision"),T("Print Process"),T("Number of Colors","number"),T("Pantone / Ink References"),T("Barcode / Regulatory Text"),T("Proof File"),T("Customer Approval Date","date"),S("Prepress Status","Draft","Proof","Customer Review","Approved","Released")],
"Die / Plate / Tooling":[T("Tool Code"),S("Tool Type","Rotary Die","Flat Die","Flexo Plate","Stereo","Cutting Form"),T("Customer Ownership"),T("Machine Compatibility"),T("Sheet / Repeat Size"),T("Number of Ups","number"),T("Storage Location"),T("Manufacture Date","date"),T("Life Limit","number"),T("Current Impressions","number"),T("Last Maintenance","date"),S("Condition","Ready","Repair","Blocked","Scrapped")],
"Carton Estimate & Quote":[T("Estimate Number"),T("Customer / Enquiry"),T("Box Design"),T("Order Quantity","number"),T("Board Area / Box","number"),T("Paper Combination"),T("Trim Waste %","number"),T("Setup Sheets","number"),T("Ink / Glue Cost","number"),T("Tooling Amortization","number"),T("Conversion Cost","number"),T("Freight / 1000","number"),T("Margin %","number"),T("Quote / 1000","number")],
"Corrugator Trim Plan":[T("Trim Plan / Deckle"),T("Production Date","date"),T("Corrugator"),T("Reel Width"),T("Paper Combination"),T("Flute"),T("Orders Combined","number"),T("Total Run Length","number"),T("Deckle Utilization %","number"),T("Expected Trim %","number"),T("Changeovers","number"),T("Schedule Sequence")],
"Corrugator Execution":[T("Run Number"),T("Trim Plan"),T("Corrugator"),T("Order / Board Grade"),T("Run Length","number"),T("Average Speed","number"),T("Good Board SqM","number"),T("Wet-end Waste","number"),T("Dry-end Waste","number"),T("Warp Reading"),T("Adhesive Consumption","number"),T("Downtime Minutes","number")],
"Printing & Slotting":[T("Job Number"),T("Customer Order"),T("Machine"),T("Artwork / Plate"),T("Number of Colors","number"),T("Anilox / Ink Set"),T("Print Repeat"),T("Slot / Score Setting"),T("Target Sheets","number"),T("Good Sheets","number"),T("Registration Waste","number"),T("Operator")],
"Die Cutting / Folder Gluer":[T("Conversion Job"),T("Order / Design"),T("Machine"),T("Die / Tool"),T("Input Sheets","number"),T("Good Output","number"),T("Die-cut Waste","number"),T("Glue Type"),T("Glue Consumption","number"),T("Bundle Size","number"),T("Machine Speed","number"),T("Quality Result")],
"Board & Box Quality":[T("Inspection Number"),T("Order / Board Lot"),T("Sample Size","number"),T("GSM Result","number"),T("Moisture %","number"),T("Burst / BF","number"),T("ECT","number"),T("BCT","number"),T("COBB","number"),T("Dimensions Result"),T("Print / Registration"),S("Disposition","Release","Hold","Rework","Reject")],
"Preventive Maintenance":[T("PM Plan"),T("Asset / Machine"),T("Maintenance Strategy"),T("Frequency"),T("Meter Trigger"),T("Task List"),T("Required Skill"),T("Estimated Hours","number"),T("Planned Spares"),T("Last Completed","date"),T("Next Due","date"),S("Compliance","On Time","Due","Overdue")],
"Breakdown Maintenance":[T("Breakdown Number"),T("Asset / Machine"),T("Reported Time","datetime-local"),T("Failure Symptom"),T("Priority"),T("Production Impact"),T("Technician"),T("Response Time (Min)","number"),T("Repair Time (Min)","number"),T("Failure Cause"),T("Corrective Action"),T("Downtime Cost","number")],
"General Ledger":[T("Journal Number"),T("Posting Date","date"),T("Document Type"),T("Ledger"),T("Company / Plant"),T("Account"),T("Cost Center"),T("Profit Center"),T("Debit","number"),T("Credit","number"),T("Currency"),T("Reference"),T("Narration","textarea")],
"Accounts Payable":[T("AP Voucher"),T("Supplier"),T("Invoice Number"),T("Invoice Date","date"),T("PO / GRN Reference"),T("Taxable Amount","number"),T("GST / Tax","number"),T("Invoice Total","number"),T("Payment Terms"),T("Due Date","date"),T("Withholding Tax","number"),S("Payment Status","Open","Part Paid","Paid","Blocked")],
"Accounts Receivable":[T("AR Invoice"),T("Customer"),T("Sales / Shipment Reference"),T("Invoice Date","date"),T("Taxable Amount","number"),T("GST / Tax","number"),T("Invoice Total","number"),T("Credit Period","number"),T("Due Date","date"),T("Receipt Amount","number"),T("Balance","number"),S("Collection Status","Current","Due","Overdue","Disputed")],
"Tax & E-Invoice":[T("Tax Document"),T("Transaction Type"),T("GSTIN"),T("Place of Supply"),T("HSN / SAC"),T("Taxable Value","number"),T("CGST","number"),T("SGST","number"),T("IGST","number"),T("IRN"),T("E-Way Bill"),S("Portal Status","Draft","Submitted","Accepted","Rejected","Cancelled")],
"Employee & Skill Matrix":[T("Employee Code"),T("Employee Name"),T("Department"),T("Plant / Line"),T("Role"),T("Primary Skill"),T("Skill Level"),T("Machine Authorization"),T("Certificate"),T("Certificate Expiry","date"),T("Shift"),S("Employment Status","Active","Leave","Contract","Inactive")],
"Incident & Near Miss":[T("Incident Number"),S("Event Type","Incident","Near Miss","Unsafe Act","Unsafe Condition"),T("Date & Time","datetime-local"),T("Plant / Location"),T("Person Involved"),T("Severity"),T("Immediate Action"),T("Medical Treatment"),T("Root Cause"),T("Corrective Action"),T("Regulatory Reportable"),S("Status","Reported","Investigating","Action Open","Closed")],
"AI Assistant":[T("Conversation / Case ID"),T("User Role"),T("Business Context"),T("Question / Request","textarea"),T("Authorized Data Scope"),T("Response Summary","textarea"),T("Evidence Links"),T("Confidence %","number"),T("Recommended Action"),T("Human Decision"),T("Feedback / Correction"),T("Model / Prompt Version")],
"Integration Monitor":[T("Integration / Interface"),S("Channel","REST API","Event","EDI","File","IoT"),T("Source System"),T("Target System"),T("Message / Correlation ID"),T("Received Time","datetime-local"),T("Processing Time (ms)","number"),T("Retry Count","number"),T("Error Code"),T("Error Detail"),T("Reconciliation Status"),S("Status","Success","Warning","Failed","Retrying","Dead Letter")],
"Vehicle Pre-Advice":[T("Appointment Number"),S("Movement Type","Purchase Inward","Sales Dispatch","Subcontract","Return","Visitor"),T("Vehicle Number"),T("Transporter"),T("Driver Name"),T("Driver Mobile"),T("PO / Shipment Reference"),T("Material / Purpose"),T("Expected Arrival","datetime-local"),T("Dock Slot"),T("Packages / Expected Weight","number"),S("Approval","Planned","Approved","Rejected","Arrived")],
"Gate In Entry":[T("Gate Entry Number"),S("Entry Type","Vehicle","Visitor","Employee","Contractor"),T("Pre-Advice / Pass Reference"),T("Vehicle / Person ID"),T("Driver / Visitor Name"),T("Document Verification"),T("Photo / ID Attachment"),T("Entry Time","datetime-local"),T("Purpose / Material"),T("Host / Receiving Department"),T("Security Officer"),S("Clearance","Allowed","Hold","Rejected")],
"Inward Gate Pass":[T("Inward Gate Pass"),T("Gate Entry Reference"),T("Supplier / Source"),T("PO / Challan Number"),T("Vehicle Number"),T("Material"),T("Package Count","number"),T("Declared Quantity","number"),T("Seal Number"),T("Receiving Dock"),T("GRN Reference"),S("Status","Entered","At Dock","Received","Returned","Closed")],
"Weighbridge Transaction":[T("Weight Slip Number"),T("Gate Entry / Shipment"),T("Vehicle Number"),S("Weighment Type","Inward","Outward","Scrap","Transfer"),T("First Weight","number"),T("First Weight Time","datetime-local"),T("Second Weight","number"),T("Second Weight Time","datetime-local"),T("Net Weight","number"),T("Expected Weight","number"),T("Variance %","number"),T("Device / Operator"),S("Status","Open","Matched","Exception","Approved")],
"Dock & Yard Management":[T("Yard Token"),T("Vehicle Number"),T("Gate Entry"),S("Activity","Unloading","Loading","Waiting","Inspection"),T("Parking Bay"),T("Dock Number"),T("Queue Position","number"),T("Dock In","datetime-local"),T("Dock Out","datetime-local"),T("Turnaround Minutes","number"),T("Coordinator"),S("Status","Queued","At Dock","Completed","Delayed")],
"Visitor Management":[T("Visitor Pass"),T("Visitor Name"),T("Company"),T("Mobile / ID"),T("Host Employee"),T("Department / Area"),T("Purpose"),T("Valid From","datetime-local"),T("Valid Until","datetime-local"),T("Belongings / Device"),T("Safety Briefing"),S("Status","Pre-approved","Inside","Exited","Expired","Blocked")],
"Employee / Contractor Access":[T("Access Event"),T("Employee / Contractor"),T("Badge / Biometric ID"),T("Employer / Department"),T("Shift / Roster"),T("Access Zone"),T("Skill / Machine Authorization"),T("Medical Valid Until","date"),T("Event Time","datetime-local"),T("Device / Gate"),T("Denial Reason"),S("Decision","Granted","Denied","Override")],
"Outward Gate Pass":[T("Outward Gate Pass"),S("Pass Type","Returnable","Non-returnable","Scrap","Sample","Tool","Material Return"),T("Requester / Department"),T("Party / Destination"),T("Material / Asset"),T("Quantity","number"),T("Vehicle / Courier"),T("Reason"),T("Expected Return","date"),T("Approval Evidence"),T("Dispatch Reference"),S("Status","Draft","Approved","Exited","Returned","Overdue")],
"Gate Out Entry":[T("Gate Exit Number"),T("Gate In Reference"),T("Vehicle / Person"),T("Outward Pass / Dispatch"),T("Weighbridge Slip"),T("Pending Material / Documents"),T("Security Checklist"),T("Exit Time","datetime-local"),T("Turnaround Minutes","number"),T("Security Officer"),T("Exception Approval"),S("Closure","Cleared","Hold","Exited")],
"Returnable Material Register":[T("Returnable Pass"),T("Material / Tool"),T("Serial / Asset Number"),T("Party / Custodian"),T("Quantity","number"),T("Sent Date","date"),T("Expected Return","date"),T("Actual Return","date"),T("Balance Quantity","number"),T("Reminder Level"),T("Condition on Return"),S("Status","Open","Part Returned","Returned","Overdue","Written Off")],
"Security Incident Register":[T("Security Incident"),S("Incident Type","Unauthorized Access","Theft","Damage","Seal Mismatch","Document Fraud","Other"),T("Event Time","datetime-local"),T("Gate / Location"),T("Person / Vehicle"),T("Description","textarea"),T("Immediate Action"),T("Evidence / CCTV Reference"),T("Investigator"),T("Root Cause"),T("Corrective Action"),S("Status","Reported","Investigating","Action Open","Closed")],
"Payroll Processing":[T("Payroll Run"),T("Payroll Period"),T("Company / Plant"),T("Employee Group"),T("Employees Processed","number"),T("Gross Earnings","number"),T("Overtime / Incentive","number"),T("Deductions","number"),T("PF / ESI / Statutory","number"),T("Tax Withheld","number"),T("Net Pay","number"),T("Accounting Document"),S("Status","Working","Validated","Approved","Posted","Paid")],
"Supplier Payment":[T("Payment Proposal"),T("Supplier"),T("AP Documents"),T("Due Amount","number"),T("Discount / Withholding","number"),T("Payment Amount","number"),T("Payment Date","date"),T("Bank Account"),T("Beneficiary Validation"),T("Approval Batch"),T("UTR / Bank Reference"),S("Status","Proposed","Approved","Sent","Success","Failed")],
"Customer Receipt":[T("Receipt Number"),T("Customer"),T("Receipt Date","date"),T("Bank / Cash Account"),T("Bank Reference"),T("Receipt Amount","number"),T("Invoices Allocated","number"),T("Allocated Amount","number"),T("Deduction / TDS","number"),T("Unapplied Amount","number"),T("Short Payment Reason"),S("Status","Draft","Posted","Reconciled","Reversed")],
"Journal Voucher":[T("Journal Voucher"),T("Posting Date","date"),T("Company / Plant"),T("Journal Type"),T("Debit Account"),T("Credit Account"),T("Amount","number"),T("Cost / Profit Center"),T("Reference Document"),T("Narration","textarea"),T("Supporting Evidence"),S("Status","Draft","Approval","Posted","Reversed")],
"Period Close & Reconciliation":[T("Close Period"),T("Company / Plant"),T("Fiscal Year"),T("AP Reconciled"),T("AR Reconciled"),T("Inventory vs GL"),T("WIP Reconciled"),T("Bank Reconciled"),T("Tax Reconciled"),T("Suspense Balance","number"),T("Close Owner"),S("Status","Open","In Progress","Exception","Closed")]
};
const groupBases={
"Home & Control Tower":[T("Workspace / KPI"),T("Reporting Period"),T("Plant / Business Unit"),T("Owner"),T("Target","number"),T("Actual","number"),T("Variance","number"),T("Alert Threshold"),T("Last Refresh","datetime-local")],
"Enterprise & Master Data":[T("Master Record Code"),T("Master Record Name"),T("Organization / Plant"),T("Effective From","date"),T("Effective To","date"),T("Owner / Steward"),T("Revision"),S("Lifecycle Status","Draft","Review","Active","Blocked","Archived")],
"CRM, Costing & Sales":[T("Commercial Document"),T("Customer / Prospect"),T("Product / Requirement"),T("Quantity","number"),T("Price / Value","number"),T("Requested Date","date"),T("Sales Owner"),T("Margin %","number"),T("Customer Status")],
"Planning & Scheduling":[T("Plan / Schedule ID"),T("Plant / Planning Area"),T("Planning Horizon"),T("Demand Quantity","number"),T("Supply Quantity","number"),T("Capacity Load %","number"),T("Shortage / Overload","number"),T("Planner"),T("Release Status")],
"Procurement & Supplier":[T("Procurement Document"),T("Supplier / Vendor"),T("Material / Service"),T("Quantity","number"),T("Commercial Value","number"),T("Required / Delivery Date","date"),T("Buyer"),T("Quality Status"),T("Approval Status")],
"Inventory, Warehouse & Logistics":[T("Inventory Document"),T("Material / Product"),T("Lot / Roll / Pallet"),T("From Location"),T("To Location"),T("Quantity","number"),T("UoM"),T("Movement Date","date"),T("Inventory Status")],
"Gate, Security & Weighbridge":[T("Gate / Security Document"),T("Vehicle / Person"),T("Reference / Purpose"),T("Gate / Location"),T("Entry Time","datetime-local"),T("Exit Time","datetime-local"),T("Security Officer"),T("Exception / Approval"),T("Clearance Status")],
"Shared Manufacturing & MES":[T("Manufacturing Document"),T("Work Order / Product"),T("Operation"),T("Machine / Resource"),T("Operator / Shift"),T("Planned Quantity","number"),T("Good Quantity","number"),T("Scrap / Rework","number"),T("Execution Status")],
"Quality Management":[T("Quality Document"),T("Item / Lot / Order"),T("Inspection Stage"),T("Characteristic / Defect"),T("Specification / Tolerance"),T("Sample Size","number"),T("Result"),T("Inspector / Owner"),T("Disposition")],
"Maintenance & Utilities":[T("Maintenance Document"),T("Asset / Equipment"),T("Maintenance Type"),T("Priority / Criticality"),T("Planned Start","datetime-local"),T("Technician"),T("Downtime Minutes","number"),T("Spares Cost","number"),T("Work Status")],
"Finance, Cost & Compliance":[T("Financial Document"),T("Party / Account"),T("Posting Date","date"),T("Company / Plant"),T("Cost Center"),T("Tax Code"),T("Debit / Amount","number"),T("Credit / Balance","number"),T("Posting Status")],
"People, Safety & Sustainability":[T("Record / Event ID"),T("Person / Metric"),T("Department / Plant"),T("Date / Period","date"),T("Category"),T("Target / Requirement"),T("Actual / Result"),T("Owner"),T("Compliance Status")],
"Reports, AI & Administration":[T("Configuration / Report ID"),T("Name / Purpose"),T("Domain / Data Source"),T("Owner"),T("Schedule / Trigger"),T("Access Scope"),T("Last Run / Updated","datetime-local"),T("Result / Health"),T("Status")]
};
function inferred(desc){return desc.split(/[,.]| and /).map(x=>x.trim()).filter(x=>x.length>2&&x.length<32).slice(0,5).map((x,i)=>{const label=x.replace(/^./,c=>c.toUpperCase());const low=x.toLowerCase();const type=/date|time/.test(low)?"date":/%|quantity|count|cost|amount|value|score|rate|hours|minutes|weight|length/.test(low)?"number":"text";return T(label,type)});}
function behavior(group,title){const key=(group+" "+title).toLowerCase();let workflow=["Draft","Validate","Submit","Approve","Activate / Close"],actions=["Save Draft","Submit for Approval","Duplicate","Export"],validations=["Required fields and valid master references","Role and organization scope","Duplicate and effective-date checks","Attachment and reason requirements"],impacts=["No inventory or financial posting until final action"],integrations=["Document service","Notification service","Audit service"],reports=[`${title} register`,"Status and aging","Exception report"];
if(/dashboard|control tower|kpi|analytics|report/.test(key)){workflow=["Configure","Validate Data","Publish","Monitor","Retire"];actions=["Refresh","Configure KPI","Schedule","Export"];validations=["Certified data source","KPI definition and owner","Authorized data scope","Refresh timestamp and reconciliation"];impacts=["Analytical only; no transactional posting"];integrations=["Warehouse / lakehouse","Semantic model","Alert service"];reports=["KPI catalogue","Data freshness","Threshold breaches"]}
else if(/master|structure|hierarchy|calendar|workflow setup|configuration|roles|users/.test(key)){workflow=["Draft","Steward Review","Impact Check","Approve","Activate"];actions=["Save Version","Submit","Compare Revision","Activate"];validations=["Unique code and naming rule","No invalid hierarchy cycle","Effective dates do not overlap","Downstream usage impact reviewed"];impacts=["Changes future transaction defaults","Historical transactions retain prior values"];integrations=["Identity / SSO","Master-data events","Cache invalidation"];reports=["Master-data changes","Duplicate candidates","Inactive records"]}
else if(/quotation|enquiry|lead|opportunity|sales order|customer portal|order change|promise/.test(key)){workflow=["Draft","Commercial Validation","Margin / Credit Approval","Customer Confirmation","Fulfil / Close"];actions=["Recalculate","Check Availability","Submit","Confirm Order"];validations=["Customer and ship-to active","Price and margin within authority","Credit exposure within limit","Promised date is capacity-feasible"];impacts=["Confirmed order creates demand","Dispatch creates inventory issue","Invoice creates receivable and revenue"];integrations=["Customer portal / EDI","Planning ATP/CTP","Tax and e-invoice"];reports=["Order book","Margin waterfall","OTIF risk","Customer backlog"]}
else if(/purchase|rfq|supplier|subcontract|goods receipt|invoice ocr/.test(key)){workflow=["Draft","Budget / Source Check","Approval","Release to Supplier","Receive / Settle / Close"];actions=["Request Quotes","Compare Bids","Submit","Release"];validations=["Supplier approved for material/service","Budget and approval authority available","Price/tax/terms match source","Receipt and invoice tolerances respected"];impacts=["PO creates commitment","GRN increases stock and receipt accrual","Invoice creates AP liability","Payment clears supplier balance"];integrations=["Supplier portal / email","Inventory and quality","AP, tax and banking"];reports=["Open commitments","Supplier OTIF","Purchase price variance","Match exceptions"]}
else if(/gate|security|visitor|vehicle|weighbridge|yard|dock|returnable material|access/.test(key)){workflow=["Pre-advised / Requested","Security Validation","Gate In / First Event","Operational Clearance","Gate Out / Close"];actions=["Verify Documents","Capture Entry","Place Hold","Clear / Close"];validations=["Vehicle/person identity and authorization valid","PO, shipment, pass or host reference available","Weight, seal and document exceptions resolved","No pending returnable item or clearance at exit"];impacts=["Creates immutable gate and access event","May trigger GRN, dispatch, attendance or returnable register","No inventory/financial posting without referenced business document"];integrations=["ANPR / camera / biometric","Weighbridge / RFID / barcode","Purchase, warehouse, dispatch, HR and security alerts"];reports=["Vehicles inside plant","Gate turnaround time","Weight and access exceptions","Returnable material aging"]}
else if(/inventory|warehouse|put-away|picking|transfer|count|packing|dispatch|rfid|barcode|traceability/.test(key)){workflow=["Created","Validated","Allocated / Scanned","Posted","Reconciled / Closed"];actions=["Scan","Allocate","Post Movement","Reverse"];validations=["Lot/status eligible for movement","Quantity cannot exceed available stock","From/to locations valid and compatible","Duplicate device event blocked"];impacts=["Posts append-only stock-ledger movement","Updates reservation and availability","Creates valuation entry where applicable"];integrations=["Barcode / RFID devices","WMS / transport","Quality status and finance valuation"];reports=["Stock ledger","Location balance","Movement exceptions","Trace genealogy"]}
else if(/forecast|s&op|schedule|planning|mrp|capacity|allocation/.test(key)){workflow=["Working Version","Calculate","Planner Review","Approve","Release / Freeze"];actions=["Run Plan","Simulate","Resolve Exceptions","Release"];validations=["Demand and supply horizon consistent","Material and capacity calendars current","Frozen-zone changes require authority","Plan totals reconcile to source demand"];impacts=["Released plan creates planned supply/demand","No financial posting","May reserve material or capacity"];integrations=["Sales demand","Procurement and production","Inventory and capacity calendars"];reports=["Plan attainment","Shortage list","Capacity load","Reschedule messages"]}
else if(/work order|manufacturing|production|operation|wip|oee|weaving|knitting|dyeing|finishing|sewing|corrugator|printing|die cutting|folder gluer|warping|cut plan/.test(key)){workflow=["Created","Readiness Check","Released","In Execution","Confirmed / Closed"];actions=["Check Readiness","Release","Start / Stop","Confirm Output"];validations=["Released BOM/recipe/routing revision","Material, machine and operator available","Quality hold blocks consumption","Good + scrap + rework reconcile to input/yield"];impacts=["Issues or backflushes material","Receives WIP / finished output","Captures labor, machine, waste and variance cost"];integrations=["Shop-floor terminal / machine","Inventory and quality","Maintenance and costing"];reports=["Production order status","Yield and waste","OEE / downtime","Actual vs standard cost"]}
else if(/quality|inspection|nonconformance|capa|complaint|calibration|shade|lab dip/.test(key)){workflow=["Plan / Record","Inspect / Investigate","Review","Disposition / Approve","Verify / Close"];actions=["Record Result","Place Hold","Create NCR / CAPA","Release"];validations=["Inspection plan and instrument valid","Sample and mandatory characteristics complete","Failed result requires disposition","Closure requires effectiveness evidence"];impacts=["May block or release inventory","Scrap/rework creates cost impact","Complaint/CAPA remains linked to traceability"];integrations=["Inventory status","Supplier/customer quality","Calibration and document evidence"];reports=["Defect Pareto","First-pass yield","CAPA aging","Supplier/customer quality"]}
else if(/maintenance|asset|breakdown|condition|spare|tool|utilities|energy/.test(key)){workflow=["Reported / Due","Plan","Approve / Permit","Execute","Verify / Close"];actions=["Plan Work","Reserve Spares","Start Work","Complete"];validations=["Asset and meter reading valid","Safety isolation / permit complete","Technician skill authorized","Failure cause and downtime required at close"];impacts=["Issues spare-parts inventory","Charges labor/material to asset or cost center","Updates meter, history and next due date"];integrations=["Production downtime","Inventory spares","Safety permit and finance"];reports=["PM compliance","MTBF / MTTR","Maintenance cost","Asset downtime"]}
else if(/ledger|payable|receivable|bank|tax|asset|cost|profitability|budget|cash forecast/.test(key)){workflow=["Draft","Accounting Validation","Approval","Post","Reconcile / Close"];actions=["Validate","Submit","Post","Reverse"];validations=["Debit equals credit","Period and account open","Tax and dimensions valid","Posted entry can only be reversed, never edited"];impacts=["Creates immutable accounting journal","Updates subledger and balance","Reversal references original posting"];integrations=["Tax / e-invoice","Banking","Inventory and production costing"];reports=["Trial balance","Subledger reconciliation","Tax register","Profitability / variance"]}
else if(/employee|attendance|training|incident|permit|waste|water|carbon|chemical|manpower|recruitment|joining|leave|overtime|payroll|payslip|appraisal|separation/.test(key)){workflow=["Record / Request","Manager Validation","HR / Compliance Review","Approve / Process","Post / Close"];actions=["Save","Validate","Submit / Process","Close"];validations=["Person, employment and organization valid","Roster, attendance, skill and approval consistent","Bank/statutory/sensitive data access restricted","Expiry, payroll and exit dependencies cleared"];impacts=["Updates workforce availability and compliance","May control gate/machine authorization","Payroll posts expense, liability and bank entries where applicable"];integrations=["Identity / biometric / gate","Shop-floor and EHS authorization","Payroll, banking and finance"];reports=["Headcount and attendance","Skill/training expiry","Payroll and overtime","Compliance and separation"]}
else if(/integration|audit trail|system health|data import|ocr review|ai assistant/.test(key)){workflow=["Received / Created","Validate","Process","Review Exception","Complete / Archive"];actions=["Validate","Process / Retry","Approve Correction","Reconcile"];validations=["Schema and authorization valid","Idempotency / duplicate control","Control totals reconcile","Sensitive fields masked"];impacts=["Posting occurs only through target domain service","All retry/correction actions audited"];integrations=["API gateway / event bus","Document / OCR service","Observability and support"];reports=["Processing health","Error aging","Retry outcomes","Control-total reconciliation"]}
return{workflow,actions,validations,impacts,integrations,reports,primaryAction:actions[1]||actions[0],prefix:title.split(/\s+/).map(x=>x[0]).join("").replace(/[^A-Z]/g,"").slice(0,4)||"DOC"}}
function schema(group,title,desc){const fields=exact[title]||[T(`${title} ID`),T(`${title} Name / Reference`),...(groupBases[group]||groupBases["Reports, AI & Administration"]).slice(2),...inferred(desc)];const unique=[];const seen=new Set();for(const f of fields){if(!seen.has(f[0])){seen.add(f[0]);unique.push(f)}}const grid=[`${title} No.`,...unique.slice(1).map(x=>x[0]).filter(c=>c!=="Owner"&&c!=="Status").slice(0,5),"Owner","Status"];return{fields:unique.slice(0,14),grid,lineTitle:/BOM|Recipe|Order|Estimate|Quotation|Purchase|Receipt|Invoice|Work Order|Plan|Schedule|Execution|Inspection|Maintenance|Journal|Budget/.test(title)?"Lines / Components / Operations":"Related Details",lineColumns:["Item / Activity","Description","Quantity","UoM","Rate / Result","Amount / Status"],...behavior(group,title)}}
window.PRODX_SCHEMA=schema;
})();
